WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

ASTEROID_BIG = 3
ASTEROID_MED = 2
ASTEROID_SMALL = 1

PLAYER_SPEED = 75
PLAYER_ACCELERATION = 75
PLAYER_DIR_SPEED = math.rad(360)
PLAYER_DIR_ACCELERATION = PLAYER_DIR_SPEED * 1.5
PLAYER_HEIGHT = 8
PLAYER_WIDTH = 8
PLAYER_INVINCIBILITY_TIMER = 1.5
PLAYER_INVINCIBILITY_FLASH = 2
BULLET_SPEED = 150
BULLET_SIZE = 1
BULLET_LIFETIME = 1.5

UFO_SHOOT_EVERY = 2
UFO_BULLET_SPEED = 75
UFO_BULLET_LIFETIME = 1